### PR TITLE
fix: support more options for externals

### PR DESCRIPTION
**Pull request by alexkrolick**
See #1

### CODE REVIEW

**Comment by alexkrolick** [comment]
The `dist` output does not have the same structure as what's on NPM (`dist/main` is a folder when I build it locally, and just a file on NPM: https://unpkg.com/grid-react-adapter@1.6.2/dist/

I branched off master, where should I be branching from?

**Comment by alexkrolick** [comment]
How are you building? When I run `npm run build` I get this:

image

Instead of:

image

**Comment by scamden** [comment]
oh the build difference is because we do `npm run build:lib` on circleci

**Comment by scamden** [comment]
you don't really need to build locally anyway, just run `npm run dev` for testing

**Pull request merged**
